name: Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 15 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions: write-all
    container: artixlinux/artixlinux:latest
    steps:
    - uses: actions/checkout@v4

    - name: build
      if: always()
      run: |
        pacman -Syu --noconfirm base-devel strace patchelf curl wget \
          desktop-file-utils git artix-archlinux-support llvm mesa xorg-server-xvfb \
          vulkan-radeon vulkan-intel vulkan-nouveau
        pacman-key --init && pacman-key --populate archlinux
        printf "\n[extra]\nInclude = /etc/pacman.d/mirrorlist-arch\n" | tee -a /etc/pacman.conf
        pacman -Syu --noconfirm zsync nss chromium gtk3 wayland libva libtiff \
          libxcb xcb-util-keysyms gvfs libepoxy highway libheif libjxl x265 \
          xcb-util-cursor gtkmm3

        chmod +x ./*-appimage.sh && ./*-appimage.sh
        mkdir dist
        mv *.AppImage* dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: AppImage
        path: 'dist'

  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4.1.8
          with:
            name: AppImage

        #Continuous Release
        - name: Continuous Releaser
          uses: softprops/action-gh-release@v2
          with:
            name: "Continuous build"
            tag_name: "continuous"
            prerelease: false
            draft: false
            generate_release_notes: false
            make_latest: true
            files: |
              *.AppImage*
          continue-on-error: false

        #Snapshot Release
        - name: Get Date
          run: |
            SNAPSHOT_TAG="$(date --utc +'%Y%m%d-%H%M%S')"
            echo SNAPSHOT_TAG="${SNAPSHOT_TAG}" >> "${GITHUB_ENV}"
          continue-on-error: false
        - name: Snapshot Releaser
          uses: softprops/action-gh-release@v2
          with:
            name: "Snapshot build"
            tag_name: "${{ env.SNAPSHOT_TAG}}"
            prerelease: true
            draft: false
            generate_release_notes: false
            make_latest: false
            files: |
              *.AppImage*
          continue-on-error: false
